Castano.Web/Models/Evento.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Castano.Web.Models
{
    public class Evento
    {
        DateTime Dia { get; set; }
        public string Cliente { get; set; }
        public string Salon { get; set; }
        public string Nombre { get; set; }

        public Evento(string Linea, int NumeroFila)
        {
            var separador = new List<string>
                    {
                        ";",
                        "\t",
                        ",",
                        " "
                    };

            var data = Linea.Split(separador.ToArray(), StringSplitOptions.RemoveEmptyEntries).ToArray();

            var parseDia = DateTime.TryParse(data[0], out DateTime dia);

            if (!parseDia)
                throw new Exception(string.Format("El archivo tiene un error en la fila {0}", NumeroFila));

            Dia = dia;
            Cliente = data[1];
            Salon = data[2];
            Nombre = data[3];
        }
    }
}

Castano.Web/Models/Pedido.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Castano.Web.Models
{
    public class Pedido
    {
        public string Salon { get; set; }

        public DateTime? Prueba { get; set; }

        public DateTime? Inicio { get; set; }

        public DateTime? Finalizacion { get; set; }

        public int CantidadDias => Inicio.HasValue && Finalizacion.HasValue 
            ? (Finalizacion.Value - Inicio.Value).Days 
            : 0;
    }
}

Castano.Web/Controllers/EventoController.cs
using Castano.Web.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Castano.Web.Controllers
{
    public class EventoController : Controller
    {
        // GET: Evento
        public ActionResult Index()
        {
            return View();
        }

        // GET: Evento/UploadFile
        public ActionResult UploadFile()
        {
            return View();
        }

        // POST: Evento/UploadFile
        [HttpPost]
        public ActionResult UploadFile(string Password)
        {
            if(Password != "CAST2458")
                return View();

            
            var file = Request.Files[0];
            if (file != null && file.ContentLength > 0)
            {
                using (StreamReader memStream = new StreamReader(file.InputStream))
                {
                    var content = memStream.ReadToEnd();
                    //
                    if (string.IsNullOrEmpty(content)) throw new ApplicationException("El archivo está vacio.");

                    var filas = content.Trim().Split(new string[] { Environment.NewLine }, StringSplitOptions.RemoveEmptyEntries).Skip(1);
                    var numeroFila = 2;
                    List<Evento> eventos = new List<Evento>();
                    foreach (var fila in filas)
                    {
                        var evento = new Evento(fila, numeroFila);

                        eventos.Add(evento);

                        numeroFila++;
                    }

                    ViewBag.Success = "Se agregaron los eventos.";
                    return View(eventos);
                }
            }
            return View();
        }
    }
}

Castano.Web/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Castano.Web.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

Castano.Web/Controllers/PedidoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Castano.Web.Controllers
{
    public class PedidoController : Controller
    {
        // GET: Pedido
        public ActionResult Create(string envioCorrecto, string envioIncorrecto)
        {
            if (!string.IsNullOrWhiteSpace(envioCorrecto)) ViewBag.Success = envioCorrecto;
            if (!string.IsNullOrWhiteSpace(envioIncorrecto)) ViewBag.Error = envioIncorrecto;
            return View();
        }

        [HttpPost]
        public ActionResult Create(Models.Pedido pedido)
        {
            if(!pedido.Prueba.HasValue || !pedido.Inicio.HasValue || !pedido.Finalizacion.HasValue)
                return RedirectToAction("Create", new { envioIncorrecto = "Su pedido no ha podido enviarse. Aguarde un momento y vuelva a intentarlo." });

            //TODO: envio por correo a info@castano
            return RedirectToAction("Create", new { envioCorrecto = "Su pedido se envió éxitosamente. Estaremos comunicándonos con usted a la brevedad." });
        }
    }
}

Castano.Web/Views/Evento/Index.cshtml
@{
    ViewBag.Title = "Eventos Castano";
}
@section content {
    @Html.Partial("_DatatablesContent")
}
<!-- Navigation -->
<nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav">
    <div class="container">
        <a class="navbar-brand js-scroll-trigger" href="@Url.Action("Index", "Home")">
            <img alt="castano&asociados" src="~/img/logo.jpg" style="max-width: 250px" />
        </a>
    </div>
</nav>
<!--Table-->
<section>
    <div class="container">
        <div class="row">
            <div class="col-lg-12 mx-auto text-center">
                <h2 class="section-heading text-primary">Nuestros Eventos</h2>
                <hr class="my-4">
                <table id="table" class="table table-striped table-bordered" style="width:100%;">
                    <thead>
                        <tr>
                            <th></th>
                            <th>Día</th>
                            <th>Cliente</th>
                            <th>Salón</th>
                            <th>Nombre</th>
                        </tr>
                    </thead>
                </table>
            </div>
        </div>
    </div>
</section>
<!--Carrusel-->
<section class="bg-primary" id="eventos">
    <div class="container-fluid text-center p-0">
        <h2 class="section-heading text-white">Destacados</h2>
        <hr class="light my-4">
        <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
            <ol class="carousel-indicators">
                <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
                <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
                <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
            </ol>
            <div class="carousel-inner" role="listbox">
                <div class="carousel-item active" style="background-image: url('img/carousel01.jpg')">
                    <div class="carousel-caption d-none d-sm-block carousel-text">
                        <h3>IDEA</h3>
                        <h5>26 de julio de 2016 / Salón Francés, RESTAURANT MERCURIO</h5>
                        <p>IDEA Centro realiza la 3er. Cena Foro del Ciclo 2016.</p>
                    </div>
                </div>
                <div class="carousel-item" style="background-image: url('img/carousel02.jpg')">
                    <div class="carousel-caption d-none d-sm-block carousel-text">
                        <h3>GRUPO BLUM</h3>
                        <h5>24 de julio de 2015 / Salón Barcelona, RIVIERA PALACE HOTEL</h5>
                        <p>Almuerzo "Día del Amigo" con que el GRUPO BLUM agasaja a sus clientes frecuentes.</p>
                    </div>
                </div>
                <div class="carousel-item" style="background-image: url('img/carousel03.jpg')">
                    <div class="carousel-caption d-none d-sm-block carousel-text">
                        <h3>BIOTOSCANA</h3>
                        <h5>22 de julio de 2016 / Salón Lamorak, HOLIDAY INN</h5>
                        <p>Seminario "Actualización en HAP 2016".</p>
                    </div>
                </div>
            </div>
            <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="sr-only">Prev</span>
            </a>
            <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="sr-only">Next</span>
            </a>
        </div>
    </div>
</section>

@section scripts {
    @Html.Partial("_DatatablesScripts")
    @Html.Partial("_DatatablesStartup", "table")
}

Castano.Web/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

Castano.Web/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Castano.Web/Views/Home/Index.cshtml
@{
    ViewBag.Title = "CASTANO & asociados";
}
<div class="body">
    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav">
        <div class="container">
            <a class="navbar-brand js-scroll-trigger" href="#page-top">
                <img alt="castano&asociados" src="~/img/logo.jpg" style="max-width: 250px" />
            </a>
            <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item">
                        <a class="nav-link js-scroll-trigger" href="#quienessomos">Quienes Somos</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link js-scroll-trigger" href="#servicios">Servicios</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link js-scroll-trigger" href="#eventos">Eventos</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    <!--Encabezado-->
    <header class="masthead text-center text-white d-flex">
        <div class="container my-auto">
            <div class="row">
                <div class="col-lg-10 mx-auto">
                    <h1 class="text-uppercase">
                        <strong>CASTANO</strong>
                    </h1>
                    <h1>
                        &amp; asociados
                    </h1>
                    <hr />
                </div>
                <div class="col-lg-8 mx-auto">
                    <h5 class="text-faded mb-5">
                        Más de 40 años proyectando el futuro
                    </h5>
                    <a class="btn btn-primary btn-xl js-scroll-trigger" href="#quienessomos">Quiénes somos</a>
                </div>
            </div>
        </div>
    </header>
    <!--Quienes somos-->
    <section class="bg-primary" id="quienessomos">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 mx-auto text-center">
                    <h2 class="section-heading text-white">Quiénes somos</h2>
                    <hr class="light my-4">
                    <p class="text-faded mb-4">
                        CASTANO & asociados es una empresa dedicada enteramente al desarrollo de servicios integrales de imagen y sonido,
                        iniciada por Francisco J. Cástano en el año 1976. La cuidadosa atención de nuestro personal capacitado y la permanente
                        actualización de nuestro equipamiento, nos permite garantizar resultados de óptima calidad, asumiendo un compromiso
                        total con el éxito de cada proyecto.
                    </p>
                    <a class="btn btn-light btn-xl js-scroll-trigger" href="#servicios">Servicios</a>
                </div>
            </div>
        </div>
    </section>
    <!--Servicios-->
    <section id="servicios">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 mx-auto text-center">
                    <h2 class="section-heading text-primary">Nuestros Servicios</h2>
                    <hr class="my-4">
                    <div class="row">
                        <div class="col-lg-3 col-md-6 text-center">
                            <div class="service-box mt-5 mx-auto">
                                <i class="fas fa-4x fa-microphone text-primary mb-3 sr-icon-1"></i>
                                <h3 class="mb-3">Sonido Profesional</h3>
                                <p class="text-muted mb-0">
                                    Contamos con una amplia gama que va desde un sonido básico hasta un sistema de sonido de alto impacto
                                </p>
                            </div>
                        </div>
                        <div class="col-lg-3 col-md-6 text-center">
                            <div class="service-box mt-5 mx-auto">
                                <i class="fas fa-4x fa-video text-primary mb-3 sr-icon-2"></i>
                                <h3 class="mb-3">Proyección</h3>
                                <p class="text-muted mb-0">
                                    Nuestro servicio de proyección cuenta con equipos de última generación
                                </p>
                            </div>
                        </div>
                        <div class="col-lg-3 col-md-6 text-center">
                            <div class="service-box mt-5 mx-auto">
                                <i class="fas fa-4x fa-broadcast-tower text-primary mb-3 sr-icon-3"></i>
                                <h3 class="mb-3">Traducción Simultánea</h3>
                                <p class="text-muted mb-0">
                                    Brindamos el confort necesario a los traductores para que lleven adelante su labor de forma óptima
                                </p>
                            </div>
                        </div>
                        <div class="col-lg-3 col-md-6 text-center">
                            <div class="service-box mt-5 mx-auto">
                                <i class="fas fa-4x fa-users text-primary mb-3 sr-icon-4"></i>
                                <h3 class="mb-3">Personal Idóneo</h3>
                                <p class="text-muted mb-0">
                                    Nuestro personal cuenta con los conocimientos necesarios para cumplir con su deber
                                </p>
                            </div>
                        </div>
                    </div>
                    <p></p>
                    <a class="btn btn-primary btn-xl js-scroll-trigger" href="#eventos">Eventos</a>
                </div>
            </div>
        </div>
    </section>
    <!--Eventos-->
    <section class="bg-primary" id="eventos">
        <div class="container-fluid text-center p-0">
            <h2 class="section-heading text-white">Nuestros Eventos</h2>
            <hr class="light my-4">
            <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
                <ol class="carousel-indicators">
                    <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
                    <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
                    <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
                </ol>
                <div class="carousel-inner" role="listbox">
                    <div class="carousel-item active" style="background-image: url('img/carousel01.jpg')">
                        <div class="carousel-caption d-none d-sm-block carousel-text">
                            <h3>IDEA</h3>
                            <h5>26 de julio de 2016 / Salón Francés, RESTAURANT MERCURIO</h5>
                            <p>IDEA Centro realiza la 3er. Cena Foro del Ciclo 2016.</p>
                        </div>
                    </div>
                    <div class="carousel-item" style="background-image: url('img/carousel02.jpg')">
                        <div class="carousel-caption d-none d-sm-block carousel-text">
                            <h3>GRUPO BLUM</h3>
                            <h5>24 de julio de 2015 / Salón Barcelona, RIVIERA PALACE HOTEL</h5>
                            <p>Almuerzo "Día del Amigo" con que el GRUPO BLUM agasaja a sus clientes frecuentes.</p>
                        </div>
                    </div>
                    <div class="carousel-item" style="background-image: url('img/carousel03.jpg')">
                        <div class="carousel-caption d-none d-sm-block carousel-text">
                            <h3>BIOTOSCANA</h3>
                            <h5>22 de julio de 2016 / Salón Lamorak, HOLIDAY INN</h5>
                            <p>Seminario "Actualización en HAP 2016".</p>
                        </div>
                    </div>
                </div>
                <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                    <span class="sr-only">Prev</span>
                </a>
                <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
                    <span class="carousel-control-next-icon" aria-hidden="true"></span>
                    <span class="sr-only">Next</span>
                </a>
            </div>
            <p></p>
            <a class="btn btn-light btn-xl js-scroll-trigger" href="@Url.Action("Index", "Evento")">Más Eventos</a>
        </div>
    </section>
</div>

Castano.Web/Views/Pedido/Create.cshtml
@model Castano.Web.Models.Pedido

@{
    ViewBag.Title = "Pedido Cástano y Asociados";

    @Styles.Render("~/Content/bootstrap.datetime")
}
<!-- Navigation -->
<div class="row">
    <nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav">
        <div class="container">
            <a class="navbar-brand js-scroll-trigger" href="@Url.Action("Index", "Home")">
                <img alt="castano&asociados" src="~/img/logo.jpg" style="max-width: 250px" />
            </a>
        </div>
    </nav>
</div>

<div class="container">
    @using (Html.BeginForm("Create", "Pedido", FormMethod.Post))
    {
        <section>
            @if (!string.IsNullOrWhiteSpace(ViewBag.Success))
            {
                <div class="alert alert-success alert-dismissible fade show" role="alert">
                    <strong>Éxito!</strong> @ViewBag.Success.
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
            }
            @if (!string.IsNullOrWhiteSpace(ViewBag.Error))
            {
                <div class="alert alert-danger alert-dismissible fade show" role="alert">
                    <strong>Error!</strong> @ViewBag.Error.
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
            }

            <!-- EVENTO -->
            <div class="container">
                <label>EVENTO</label>
                <div class="form-group">
                    @Html.LabelFor(m => Model.Salon)
                    <div class="col-xs-10 col-lg-5">
                        <input type="text" id="Salon" name="Salon" class="form-control" data-bind="value: Salon" />
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(m => Model.Prueba)
                    <div class="col-xs-10 col-lg-5">
                        <div class="form-group">
                            <div class="input-group date" id="Prueba" data-target-input="nearest">
                                <input type="text" class="form-control datetimepicker-input" name="Prueba" data-target="#Prueba" data-bind="dateString: Prueba, datePattern: 'DD/MM/YYYY HH:mm'" />
                                <div class="input-group-append" data-target="#Prueba" data-toggle="datetimepicker">
                                    <div class="input-group-text"><i class="fa fa-calendar"></i></div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(m => Model.Inicio)
                    <div class="col-xs-10 col-lg-5">
                        <div class="form-group">
                            <div class="input-group date" id="Inicio" data-target-input="nearest">
                                <input type="text" class="form-control datetimepicker-input" name="Inicio" data-target="#Inicio" data-bind="dateString: Inicio" />
                                <div class="input-group-append" data-target="#Inicio" data-toggle="datetimepicker">
                                    <div class="input-group-text"><i class="fa fa-calendar"></i></div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(m => Model.Finalizacion)
                    <div class="col-xs-10 col-lg-5">
                        <div class="form-group">
                            <div class="input-group date" id="Finalizacion" data-target-input="nearest">
                                <input type="text" class="form-control datetimepicker-input" name="Finalizacion" data-target="#Finalizacion" data-bind="dateString: Finalizacion" />
                                <div class="input-group-append" data-target="#Finalizacion" data-toggle="datetimepicker">
                                    <div class="input-group-text"><i class="fa fa-calendar"></i></div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(m => Model.CantidadDias)
                    <div class="col-xs-10">
                        <label data-bind="text: CantidadDias"></label>
                    </div>
                </div>
            </div>

            <!-- EQUIPAMIENTO -->
            <div class="container">
                <label>EQUIPAMIENTO</label>

                <div class="form-group">

                </div>
            </div>

            <hr />

            <!--SUBMIT-->
            <div class="container">
                <div class="form-group">
                    <div class="col-xs-offset-2 col-xs-10">
                        <button type="submit" class="btn btn-primary">Enviar</button>
                    </div>
                </div>
            </div>

        </section>
    }
</div>

@Scripts.Render("~/bundles/bootstrap.datetime")
@Scripts.Render("~/bundles/knockout")

<script type="text/javascript">
    $(document).ready(function () {
        $('#Prueba').datetimepicker({
            stepping: 15,
            minDate: moment(new Date()).add(1, 'days'),
            sideBySide: true
        });
        $('#Inicio').datetimepicker({
            stepping: 15,
            sideBySide: true
        });
        $('#Finalizacion').datetimepicker({
            stepping: 15,
            sideBySide: true
        });

        $("#Prueba").on("change.datetimepicker", function (e) {
            $('#Inicio').datetimepicker('minDate', moment(e.date).add(1, 'hour'));
        });
        $("#Inicio").on("change.datetimepicker", function (e) {
            $('#Finalizacion').datetimepicker('minDate', moment(e.date).add(1, 'hour'));
        });

        //
        ko.validation.init({
            errorElementClass: 'has-error',
            errorMessageClass: 'help-block',
            decorateInputElement: true
        });

        function modelPedido() {
            this.Salon = ko.observable('');
            this.Prueba = ko.observable();
            this.Inicio = ko.observable();
            this.Finalizacion = ko.observable();

            this.CantidadDias = ko.pureComputed(function () {
                var momentFinalizacion = moment(this.Finalizacion());
                var momentInicio = moment(this.Inicio());
                var diferencia = momentFinalizacion.diff(momentInicio, 'days');
                return this.Salon() + " " + this.Finalizacion() + " " + this.Inicio();
            }, this);
        };

        ko.applyBindings(modelPedido);
    });
</script>

Castano.Web/Views/Shared/_DatatablesContent.cshtml
<link href="~/css/datatables/datatablesBs4.css" rel="stylesheet" />
<link href="~/css/datatables/datatablesButtonsBs4.css" rel="stylesheet" />
<link href="~/css/datatables/datatablesResponsiveBs4.css" rel="stylesheet" />

Castano.Web/Views/Shared/_DatatablesScripts.cshtml
<script src="js/datatables/datatables.js"></script>
<script src="js/datatables/datatablesBs4.js"></script>
<script src="js/datatables/datatablesButtons.js"></script>
<script src="js/datatables/datatablesButtonsBs4.js"></script>
<script src="js/datatables/datatablesResponsive.js"></script>
<script src="js/datatables/datatablesResponsiveBs4.js"></script>
<script src="js/datatables/jszip.js"></script>
<script src="js/datatables/datatables.default.js"></script>

Castano.Web/Views/Shared/_DatatablesStartup.cshtml
@model string

<script type="text/javascript">
    $(document).ready(function () {
        $('@Model').DataTable({
            responsive: {
                details: {
                    type: 'column'
                }
            },
            columnDefs: [{
                className: 'control',
                orderable: false,
                targets: 0
            }],
            bAutoWidth: false,
            buttons: ['copyHtml5', 'excelHtml5', 'csvHtml5'],
            select: true,
            ajax: './Scripts/FileEventos/eventos.txt'
        });
    });
</script>

Castano.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>CASTANO &amp; asociados</title>

    <!-- Bootstrap core CSS -->
    @Styles.Render("~/Content/bootstrap")
    <!-- Bootstrap core JavaScript -->
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    <!-- Custom fonts for this template -->
    @Styles.Render("~/Content/fontawesome")
    <link href='//fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>
    <link href='//fonts.googleapis.com/css?family=Merriweather:400,300,300italic,400italic,700,700italic,900,900italic' rel='stylesheet' type='text/css'>
    <!-- Plugin CSS -->
    @Styles.Render("~/Content/magnific")
    <!-- Custom styles for this template -->
    @Styles.Render("~/Content/creative")

    @RenderSection("content", required: false)
</head>

<body id="page-top">

    @Scripts.Render("~/bundles/moment")
    <!-- Plugin JavaScript -->
    @Scripts.Render("~/bundles/jquery.easing")
    @Scripts.Render("~/bundles/scrollreveal")
    @Scripts.Render("~/bundles/magnific.popup")
    <!-- Custom scripts for this template -->
    @Scripts.Render("~/bundles/creative")
    <!--Facebook plugin-->
    <script>
        (function (d, s, id) {
            var js, fjs = d.getElementsByTagName(s)[0];
            if (d.getElementById(id)) return;
            js = d.createElement(s); js.id = id;
            js.src = 'https://connect.facebook.net/es_ES/sdk.js#xfbml=1&version=v3.2';
            fjs.parentNode.insertBefore(js, fjs);
        }(document, 'script', 'facebook-jssdk'));
    </script>

    @RenderSection("scripts", required: false)

    @RenderBody()
    <hr />
    <footer>
        <div class="container">
            <div class="row text-center">
                <div class="col-lg-6">
                    <div id="fb-root"></div>
                    <div class="fb-page" data-href="https://www.facebook.com/CASTANO-asociados-154095021324925/" data-width="500" data-small-header="false" data-adapt-container-width="true" data-hide-cover="false" data-show-facepile="false">
                        <blockquote cite="https://www.facebook.com/CASTANO-asociados-154095021324925/" class="fb-xfbml-parse-ignore">
                            <a href="https://www.facebook.com/CASTANO-asociados-154095021324925/">CASTANO &amp; asociados</a>
                        </blockquote>
                    </div>
                </div>
                <div class="col-lg-2 text-primary">
                    <i class="fas fa-map-marker-alt fa-3x mb-3 sr-icon-1"></i>
                    <p>Rosario, Santa Fe</p>
                    <p>2000</p>
                </div>
                <div class="col-lg-2 text-primary">
                    <i class="fas fa-phone fa-3x mb-3 sr-icon-2"></i>
                    <p>&nbsp;(0341)485-4531</p>
                </div>
                <div class="col-lg-2 text-primary">
                    <i class="fas fa-envelope fa-3x mb-3 sr-icon-3"></i>
                    <p>
                        &nbsp;<a href="mailto:info@castanoyasociados.com.ar">info@castanoyasociados</a>
                    </p>
                </div>
            </div>
            <hr class="my-4">
            <div class="row">
                <div class="col-lg-6 mr-auto text-center">
                    <h5>
                        CASTANO &amp; asociados &copy; @DateTime.Now.Year
                    </h5>
                </div>
                <div class="col-lg-6 mr-auto text-right">
                    <small>
                        Diseño y desarrollo:
                        <a href="mailto:casasmanuj@gmail.com.ar">
                            Manuel J. Casas
                        </a>
                    </small>
                </div>
            </div>
        </div>
    </footer>

</body>
</html>